i=0;
j = 0;
emoName[i] = "energy";
emoValue[i] = 0.5;
emoLightIncrease[i,j] = -1/10; j++;
emoLightIncrease[i,j] = -1/30; j++;
emoLightIncrease[i,j] = 1/30; j++;
emoLightIncrease[i,j] = 1/10; j++;
emoOptimal[i] = 0.5;
